### ISSUE TITLE
jenkins-slave-nodejs10-angular build fails due to wrong formed angular version

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#305] opened 2020-05-26 15:32 UTC
**Describe the bug**
build of jenkins-slave-nodejs10-angular fails.
environment: ods dev env

```
Step 14/18 : RUN npm config set registry=$NEXUS_HOST/repository/npmjs/ &&     npm config set always-auth=true &&     npm config set _auth=$(echo -n $NEXUS_AUTH | base64) &&     npm config set email=no-reply@opendevstack.org &&     npm config set ca=null &&     npm config set strict-ssl=false &&     yarn config set registry $NEXUS_HOST/repository/npmjs/ -g &&     npm install -g @angular/cli@8.0.1 --unsafe-perm=true --allow-root &&     npm install -g cypress@3.3.1 --unsafe-perm=true --allow-root > /dev/null &&     npm --version &&     ng version &&     cypress verify
 ---> Running in 62dd5ffb5d61
/usr/local/bin/scl_enable: line 3: scl_source: No such file or directory
yarn config v1.22.4
success Set "registry" to "https://nexus-ods.172.17.0.1.nip.io/repository/npmjs/ ".
Done in 0.05s.
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! request to https://nexus-ods.172.17.0.1.nip.io/repository/npmjs/@angular%2fcli  failed, reason: connect EHOSTUNREACH 172.17.0.1:443
```

**Comment by stitakis** [comment] 2020-05-26 15:35
@michaelsauter the version of angular looks weird `@angular%2fcli` (url: `https://nexus-ods.172.17.0.1.nip.io/repository/npmjs/@angular%2fcli`).

**Comment by michaelsauter** [comment] 2020-05-27 06:42
@cschweikert Do you know how to fix this or where the error might come from?

**Comment by cschweikert** [comment] 2020-05-27 08:22
Looks like the dash within ``@angular-cli`` was url escaped to ``%2f``. This is not necessarily wrong. It depends on what the nexus repository expects. Was there an update on yarn or nexus lately?

**Comment by stitakis** [comment] 2020-05-27 08:35
@cschweikert this is the docker command used in the quickstarter to install yarn:
```
RUN curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - && \
    yum install -y nodejs && \
    yum install -y gcc-c++ make && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo && \
    yum install -y yarn && \
    yum clean all -y
```
It grabs the latest yarn, right? To isolate the problem, which version of yarn could we try? Or how could we instruct yarn/nexus to not encode "-"?

**Comment by cschweikert** [comment] 2020-05-27 08:48
I guess the problem is much simpler: https://nexus-ods.172.17.0.1.nip.io is not reachable at all. I guess this nexus is down. I had an issue with an unexpected nexus shutdown yesterday on another instance of nexus.

**Comment by clemensutschig** [comment] 2020-05-31 21:15
@stitakis was the nexus available?

**Comment by georgfedermann** [comment] 2020-06-01 10:04
Further analysis shows that this issue is caused by two other issues:
- The route https://nexus-ods.172.17.0.1.nip.io cannot be resolved in our OKD cluster from within OpenShift pods, while they can be resolved from outside OpenShift, e.g. the host machine. We applied a workaround to fix the build, and are still working on resolving the original issue of the routes not being resolvable from within OpenShift pods in OKD.
- The ods-core nexus configuration provides a repository npm-all while the Dockerfile references a repository npmjs. We implemented a workaround by adding an additional repository npmjs in the ods-core nexus repository configuration in branch feature/ods-devenv.

After applying these two workarounds, the jenkins-slave-nodejs10-angular build succeeds for us in the OKD cluster.

**Comment by clemensutschig** [comment] 2020-06-01 10:11
@georgfedermann - the missing npmjs is a bug.. ;-(

Regarding the cluster Route.. can you try to expose a service as Route and See what you get configured as default.. in the console of the ods namespace- click on create route.. und choose the service.. 

Secondly Maybe @hugowschneider  can help .. in this scripts he did some config of the cluster

**Comment by hugowschneider** [comment] 2020-06-02 09:46
@georgfedermann @clemensutschig, I had trouble making one pod talk to pods in other namespaces (I don't remember if I made this work). I did not find the `oc cluster up` command in the branch, but I used this one for having working routes from the outside:

https://github.com/opendevstack/ods-core/blob/35f174b0adf442e5ab80aeaa536005fae3b31d94/.github/workflows/continuous-integration-workflow.yml#L132
For troubleshooting, you need to see if the route can be resolved from other pods and if the requests can be routed. There is some tooling that can help you with that. 

Additionally, I believe this discussion should be a move to https://github.com/opendevstack/ods-core/pull/549 because it looks like it is related to the environment.

**Comment by georgfedermann** [comment] 2020-06-04 14:17
yes, this is fixed.

**Closed** 2020-06-04 14:18 UTC
Labels: bug
