### ISSUE TITLE
be-python-flask CoverageException("No data to report.") 

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-quickstarters#55] opened 2019-10-22 09:28 UTC
**Describe the bug**
The quickstarters jenkins build fail during the coverage state when the workspace has the name tests in it. 

**To Reproduce**

1. Deliver a change to the quickstarter with a branch name containing the word tests in it such as feature/activate-tests
2. The build fails as shown above

**Expected behavior**
build should not use the workspace directory name derived from the feature branch when omitting code. 

**Affected version (please complete the following information):**
 - Quickstarter master, 1.2.x and probably earlier

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**

The log message is as follows(excerpt):

```
Name    Stmts   Miss Branch BrPart  Cover
-----------------------------------------
Traceback (most recent call last):
  File "/tmp/workspace/project-cd/project-cd-be-python-flask-feature-activate-tests/venv/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
...
  File "/tmp/workspace/project-cd/project-cd-be-python-flask-feature-activate-tests/venv/lib/python3.6/site-packages/coverage/summary.py", line 158, in report
    raise CoverageException("No data to report.")
coverage.misc.CoverageException: No data to report.
atexit: <coverage.control.Coverage object at 0x7f3efc615a90>
```

**Additional context**

Changing the omit setting in https://github.com/opendevstack/ods-project-quickstarters/blob/1a951048067adaf80dafd05dd32a2b81461e2723/boilerplates/be-python-flask/files/src/tests/.coveragerc#L4 to 

```
omit = *src/tests*
       *__init__*
```

fixed the issue for me. 
However I am not certain this is the right approach and would also work on Windows for example. 
Updated comment for better formatting.

**Comment by adyachok** [comment] 2019-11-29 14:18
@henrjk @gerardcl I tried to reproduce the issue, however it works fine for me.(check build zo-cd-qs-flask-master (zo project jenkins jobs)).

**Comment by michaelsauter** [comment] 2019-11-29 14:26
@adyachok It looks like the source code might be old. Could you provision a new quickstarter to verify?

**Comment by adyachok** [comment] 2019-12-06 15:01
Verified on a completely new project https://jenkins-smart-cd.22ad.bi-x.openshiftapps.com/job/smart-cd/job/smart-cd-henrich-master/1/console

**Comment by henrjk** [comment] 2019-12-07 16:48
For the issue to show the workspace must have the word tests in it. In the repro attempt the workspace is at:

`/tmp/workspace/smart-cd/smart-cd-henrich-master/`

To test this you must deliver a change to the quickstarter with a branch name containing the word tests in it such as `feature/activate-tests`

**Comment by michaelsauter** [comment] 2019-12-09 08:34
@henrjk Nice find!

**Comment by adyachok** [comment] 2019-12-09 16:33
I checked it fails with "tests" in folder name. I would suggest for @henrjk to fire a bug in nose project.

**Comment by henrjk** [comment] 2019-12-10 09:31
@adyachok do you see a reason not to fix this with the proposed changes in the initial comment?

**Comment by michaelsauter** [comment] 2019-12-11 16:00
@hugowschneider @sklingel Do you have access to a Windows machine and can verify if @henrjk solution proposed in the opening comment works (generally and on Win)? That would be great, because then I propose to fix this before ODS 2.

**Comment by michaelsauter** [comment] 2019-12-12 16:37
Hmm, as this is a smaller issue and there is no progress in the last couple of days, I will take it off from ODS 2. If someone gets to fix and test it tomorrow morning, great, otherwise we move it to ODS 3.

**Comment by clemensutschig** [comment] 2020-02-07 14:54
@sklingel  - can you help fix this - we'll need this pretty soon - for the qualification work we do.

**Comment by gerardcl** [comment] 2020-03-07 13:17
Hi! I would close this issue since:
- @henrjk  provided a solution that works
- we should get rid of nosetests (not supported anymore) and move to another test suite like pytest (I strongly recommend this one)

I will provide a proposal change regarding the test suite, the idea is to make the quickstarter itself more lightweight too so to only come as an API example but without templating (no one is making use of the templating example and users just need the basis for starting using python and flask, then they decide if they want to implemente templating or any other requirement).

**Closed** 2020-03-09 20:38 UTC
