### ISSUE TITLE
ssh-agent error when using /cd/jenkins-slave-base:2.x

### ISSUE THREAD

**Issue by dwmaris** [opendevstack/ods-quickstarters#267] opened 2020-04-30 20:48 UTC
**Describe the bug**
ssh-agent error when using /cd/jenkins-slave-base:2.x
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.

**To Reproduce**
1. create an OPD Pipeline Jenkins file
2. set your image to be ${dockerRegistry}/cd/jenkins-slave-base:2.x
3. get an SSH secret from Jenkins into a variable
     sourceSecret2 = "<PROJECT><SSHSECRET>"
4. run this single method from the pipeline

def stageRun(def context) {
  stage('RUN') {
     withCredentials([sshUserPrivateKey(credentialsId: sourceSecret2, keyFileVariable: 'KEY_FILE')]) {
       sh """
         ssh-agent bash -c 'ssh-add ${KEY_FILE}
         ssh-add -L
         ssh-keyscan -p port bitbucket. >> ~/.ssh/known_hosts
         git clone ssh://git@bitbucket:port/something.git ./roles/ansible-role-satregister -v '
      """
    }
  }
}

**Expected behavior**
clone the repo

**Screenshots**
<Confidential Information>

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
email me for logs 
```

**Additional context**

**Comment by michaelsauter** [comment] 2020-05-04 06:46
It looks like this is a limitation in OpenShift, and apparently by design: https://bugzilla.redhat.com/show_bug.cgi?id=1666308.

Not sure that helps, but at least it could explain your issue ...

**Comment by clemensutschig** [comment] 2020-05-04 12:37
@dwmaris - and it stops there or does it continue?

**Comment by dwmaris** [comment] 2020-05-04 14:22
@clemensutschig - I am not sure this solves my problem. It explains the problem, that there is an  LD_PRELOAD variable set as part of the image, but it is not set as part of the "no-lfs" image. 

To be cleared: in the no-lfs image, I can run ssh-agent. on the ODS 2.0 images I cannot.

the final comment from the https://bugzilla.redhat.com/show_bug.cgi?id=1666308 is 
**"LD_PRELOAD should be used selectively not exported to the complete environment.
This is not a bug as Lukas correctly stated."**

**Comment by gerardcl** [comment] 2020-05-04 18:26
Hi @dwmaris , as mentioned, the "no-lfs" tag is a legacy image that needs to be removed at some point.
That tag is based on a huge deprectaded jenkins base image version that is no longer mantiained by redhat. 
Question: why do not use git+https?

**Comment by dwmaris** [comment] 2020-05-05 18:52
@gerardcl I do use git+https for regular Bitbucket checkouts, and that works fine. I am trying to offer the use of ansible-galaxy downloads from a requirements file. For this function, If I want to use git+https I need to SED into the requirements file the secrets on the fly. I thought this was a more complicated approach. 

I also acknowledge that the no-lfs tag is legacy. I created this bug report because I have a use case that the ODS 2.0 images does not satisfy

**Comment by dwmaris** [comment] 2020-05-05 18:54
> @dwmaris - and it stops there or does it continue?

Sorry @clemensutschig I misunderstood your question. when I get the error, the Pipeline ends with an error, and does not download the bitbucket repositories. In my example I demonstrated a simple gut clone, but my intention is to use ansible-galaxy. I get the same error with both.

**Comment by gerardcl** [comment] 2020-08-14 15:34
hi @dwmaris , did you solve this issue or shall we look into it more? it all seems like (maybe due to security reasons) that was moved out from the base images. If required we could test again within ODS3

**Comment by prathyusha-mandala** [comment] 2020-11-19 13:15
Hi @gerardcl , We have jenkins job which was running earlier and now we are receiving an error while fetching some secret from ssh-agent to do a git clone.
 ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded

**Comment by gerardcl** [comment] 2020-11-30 17:23
hi @prathyusha-mandala , is your comment in the same context of what @dwmaris reported? which ODS version are you using?

**Comment by gerardcl** [comment] 2021-02-16 10:22
Hi @prathyusha-mandala  and @dwmaris, we will close this issue in the next days if no more feedback provided. 
Please, if you test again, you should be using ODS 3.x as a baseline.

**Closed** 2021-11-09 20:00 UTC
Labels: bug
